### ISSUE TITLE
慧点oa相关问题

### ISSUE THREAD

**Issue by mssky9527** [ax1sX/SecurityList#8]
仓库中提到的文件上传，需要有绝对路径，可一般的tomcat有版本号，还有上层目录，请问能够从什么接口获取网站路径吗，我没有源码，分析不了，师傅是否能提供一下

**Comment by ax1sX** [comment]
针对tomcat版本号这个问题，可以用一些渗透的技巧，比如访问一些不存在的路径，页面会报错404 Not Found，页面下方就会爆出tomcat版本。网站路径的话，也可以在文件上传时根据报错“系统找不到指定的路径”来测试。

**Comment by mskky** [comment]
> 针对tomcat版本号这个问题，可以用一些渗透的技巧，比如访问一些不存在的路径，页面会报错404 Not Found，页面下方就会爆出tomcat版本。网站路径的话，也可以在文件上传时根据报错“系统找不到指定的路径”来测试。

非常感谢

**Comment by mssky9527** [comment]
> 针对tomcat版本号这个问题，可以用一些渗透的技巧，比如访问一些不存在的路径，页面会报错404 Not Found，页面下方就会爆出tomcat版本。网站路径的话，也可以在文件上传时根据报错“系统找不到指定的路径”来测试。

非常感谢
